docs: source docs added for moja.modules.cbm
SLEEK-TOOLS/moja.canada pull request #37
Opened 2022-08-14 10:24 UTC by Namyalg

2022-08-18 21:56 UTC, aornugent commented
Thanks @Namyalg - can you please share the link to your example? Last time I checked it was looking fantastic.

2022-08-19 05:45 UTC, Namyalg commented
Deployed link : https://namyalg.github.io/moja.canada/
It is built into the CI

2022-08-19 07:27 UTC, aornugent commented
@HarshCasper - are the CI errors permission related? Happy to merge if so.

2022-08-19 07:27 UTC, aornugent approved these changes

2022-08-19 07:30 UTC, aornugent commented on Source/moja.modules.cbm/include/moja/modules/cbm/record.h
> +        bool operator==(const PoolRecorother) const;
This looks like a typo

2022-08-19 07:31 UTC, aornugent commented on Source/moja.modules.cbm/include/moja/modules/cbm/rootbiomassequation.h
> +        inline double (double componentAbovegroundCarbon) {
This deletion doesn't look right.

2022-08-19 08:03 UTC, aornugent requested changes
@HarshCasper @radistoubalidis - can we build this branch and run the FLINTcloud integration test to check that the only documentation (and not GCBM source) has been modified.

2022-08-19 09:03 UTC, aornugent approved these changes

2022-08-19 09:09 UTC, Namyalg commented
I have gone through the changes, it will be a good idea to run a test and ensure the source code has not changed.

2022-08-30 10:31 UTC, aornugent approved these changes
@Namyalg has checked that her changes affect docs only. @mfellows - please let us know if you encounter any issues and so that we can rollback and debug.

Thanks @Namyalg for this heroic effort!

2022-08-30 10:32 UTC, merged

2022-08-30 16:25 UTC, mfellows commented
Thanks @Namyalg, that's a huge amount of work!